name: eMessage
main: network.ethereal.eMessage.eMessage
version: 1.0
depend: [TitleManager]
description: >
             Messaging System for Ethereal Network
commands:
  emsg:
    description: Basic command.
    permission: eMessage.emsg
    permission-message: You don't have permission to use that.