name: eMessage
main: network.ethereal.eMessage.eMessage
version: 1.2
description: >
             Messaging System for Ethereal Network
commands:
  emsg:
    description: Commands for starting, adding, removing, and reloading.
    permission: eMessage.emsg
    permission-message: You don't have permission to use that.